version: '3.8'

services:

  database:
    build: ./db
    container_name: db
    restart: always
    # volumes:
    #   - path/to/volume:/home/data


  java_app:
    build: ./app
    container_name: j_app
    ports:
      - 8080:8080
    # volumes:
    #   - path/to/volume:/home/fileStorage
